# Generated by Django 3.1.7 on 2021-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admodel',
            options={'verbose_name': 'Ad'},
        ),
        migrations.AlterModelOptions(
            name='advertisermodel',
            options={'verbose_name': 'Advertiser'},
        ),
        migrations.AlterModelOptions(
            name='clickmodel',
            options={'verbose_name': 'Click'},
        ),
        migrations.AlterModelOptions(
            name='viewmodel',
            options={'verbose_name': 'View'},
        ),
        migrations.AddField(
            model_name='admodel',
            name='image_url',
            field=models.CharField(default='https://img.icons8.com/plasticine/100/000000/person-male.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='admodel',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clickmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='viewmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
